# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 841)
        MainWindow.setMinimumSize(QtCore.QSize(1167, 841))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1167, 586))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(1165, 48))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 170, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(170, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon/loginIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 40))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icon/TablerProgressX (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 40))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/icon/HugeiconsMaximize03.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 40))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/src/icon/HugeiconsMinimize04.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(17)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(1165, 784))
        self.frame_3.setStyleSheet("#frame_7{\n"
"    border-bottom-right-radius:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(171, 789))
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border-bottom-left-radius:20px;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 16pt \"华文新魏\";\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(255, 170, 0);\n"
"    padding-bottom:5px;\n"
"    padding-left:5px;\n"
"}\n"
"#frame_8:hover{\n"
"    background-color: rgb(115, 148, 255);\n"
"}\n"
"#frame_9:hover{\n"
"    background-color: rgb(115, 148, 255);\n"
"}\n"
"\n"
"#frame_21:hover{\n"
"    background-color: rgb(115, 148, 255);\n"
"}\n"
"\n"
"#frame_22:hover{\n"
"    background-color: rgb(115, 148, 255);\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_21 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_10.addWidget(self.pushButton_7)
        self.verticalLayout_3.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_11.addWidget(self.pushButton_8)
        self.verticalLayout_3.addWidget(self.frame_22)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_23 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_3.addWidget(self.frame_23)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(1028, 789))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.formLayout = QtWidgets.QFormLayout(self.frame_7)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1025, 800))
        self.stackedWidget.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.firstPage = QtWidgets.QWidget()
        self.firstPage.setMinimumSize(QtCore.QSize(1066, 800))
        self.firstPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firstPage.setObjectName("firstPage")
        self.formLayout_4 = QtWidgets.QFormLayout(self.firstPage)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.frame_24 = QtWidgets.QFrame(self.firstPage)
        self.frame_24.setStyleSheet("")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 28pt \"华文新魏\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"text-align: center;\n"
"vertical-align: middle; ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_24)
        self.stackedWidget.addWidget(self.firstPage)
        self.gradeSetPage = QtWidgets.QWidget()
        self.gradeSetPage.setObjectName("gradeSetPage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.gradeSetPage)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_25 = QtWidgets.QFrame(self.gradeSetPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_25)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_25)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 6, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 8, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.gradeSetPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_26)
        self.formLayout_5.setContentsMargins(-1, 0, -1, 20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_26)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_3)
        self.verticalLayout_13.addWidget(self.frame_26)
        self.stackedWidget.addWidget(self.gradeSetPage)
        self.classSetPage = QtWidgets.QWidget()
        self.classSetPage.setObjectName("classSetPage")
        self.formLayout_6 = QtWidgets.QFormLayout(self.classSetPage)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setSpacing(0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.frame_27 = QtWidgets.QFrame(self.classSetPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 35))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 2, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 150))
        self.pushButton_10.setSizeIncrement(QtCore.QSize(0, 3))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 5, 3, 1)
        self.verticalLayout_14.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame_29)
        self.formLayout_7.setContentsMargins(5, 0, 5, 20)
        self.formLayout_7.setSpacing(0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_29)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_4)
        self.verticalLayout_14.addWidget(self.frame_29)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_27)
        self.stackedWidget.addWidget(self.classSetPage)
        self.examKindPage = QtWidgets.QWidget()
        self.examKindPage.setObjectName("examKindPage")
        self.formLayout_8 = QtWidgets.QFormLayout(self.examKindPage)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setSpacing(0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.frame_30 = QtWidgets.QFrame(self.examKindPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setMinimumSize(QtCore.QSize(160, 40))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_32 = QtWidgets.QFrame(self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_32.sizePolicy().hasHeightForWidth())
        self.frame_32.setSizePolicy(sizePolicy)
        self.frame_32.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_32)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_32)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_32)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 1, 6, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 1, 5, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 1, 4, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_32)
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_31.sizePolicy().hasHeightForWidth())
        self.frame_31.setSizePolicy(sizePolicy)
        self.frame_31.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.formLayout_9 = QtWidgets.QFormLayout(self.frame_31)
        self.formLayout_9.setContentsMargins(5, 0, 5, 20)
        self.formLayout_9.setSpacing(0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.frame_31)
        self.tableWidget_5.setMinimumSize(QtCore.QSize(55, 30))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_5)
        self.verticalLayout_15.addWidget(self.frame_31)
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_30)
        self.stackedWidget.addWidget(self.examKindPage)
        self.examSubjPage = QtWidgets.QWidget()
        self.examSubjPage.setObjectName("examSubjPage")
        self.formLayout_10 = QtWidgets.QFormLayout(self.examSubjPage)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setSpacing(0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.frame_33 = QtWidgets.QFrame(self.examSubjPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setMinimumSize(QtCore.QSize(80, 100))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_34.sizePolicy().hasHeightForWidth())
        self.frame_34.setSizePolicy(sizePolicy)
        self.frame_34.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_34)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 1, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_34)
        self.label_23.setMinimumSize(QtCore.QSize(0, 35))
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_34)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_4.addWidget(self.pushButton_12, 1, 4, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 0, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_34)
        self.label_22.setMinimumSize(QtCore.QSize(0, 35))
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 1, 3, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_35.sizePolicy().hasHeightForWidth())
        self.frame_35.setSizePolicy(sizePolicy)
        self.frame_35.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.formLayout_11 = QtWidgets.QFormLayout(self.frame_35)
        self.formLayout_11.setContentsMargins(0, 0, 5, 20)
        self.formLayout_11.setSpacing(0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.frame_35)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_6)
        self.verticalLayout_16.addWidget(self.frame_35)
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_33)
        self.stackedWidget.addWidget(self.examSubjPage)
        self.stuInfoSetPage = QtWidgets.QWidget()
        self.stuInfoSetPage.setMinimumSize(QtCore.QSize(1028, 800))
        self.stuInfoSetPage.setObjectName("stuInfoSetPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stuInfoSetPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.stuInfoSetPage)
        self.frame_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame555 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame555.sizePolicy().hasHeightForWidth())
        self.frame555.setSizePolicy(sizePolicy)
        self.frame555.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame555.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame555.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame555.setObjectName("frame555")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame555)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.frame_11 = QtWidgets.QFrame(self.frame555)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.cboGrde_2 = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboGrde_2.sizePolicy().hasHeightForWidth())
        self.cboGrde_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboGrde_2.setFont(font)
        self.cboGrde_2.setObjectName("cboGrde_2")
        self.horizontalLayout_13.addWidget(self.cboGrde_2)
        self.horizontalLayout_12.addWidget(self.frame_11)
        spacerItem18 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.frame_14 = QtWidgets.QFrame(self.frame555)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_14)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.cboClass_2 = QtWidgets.QComboBox(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboClass_2.sizePolicy().hasHeightForWidth())
        self.cboClass_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboClass_2.setFont(font)
        self.cboClass_2.setObjectName("cboClass_2")
        self.horizontalLayout_14.addWidget(self.cboClass_2)
        self.horizontalLayout_12.addWidget(self.frame_14)
        spacerItem19 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.frame_15 = QtWidgets.QFrame(self.frame555)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btnBush_2 = QtWidgets.QPushButton(self.frame_15)
        self.btnBush_2.setObjectName("btnBush_2")
        self.horizontalLayout_20.addWidget(self.btnBush_2)
        self.btnAdd_2 = QtWidgets.QPushButton(self.frame_15)
        self.btnAdd_2.setObjectName("btnAdd_2")
        self.horizontalLayout_20.addWidget(self.btnAdd_2)
        self.horizontalLayout_12.addWidget(self.frame_15)
        spacerItem20 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem20)
        self.verticalLayout_9.addWidget(self.frame555)
        self.frame666 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame666.sizePolicy().hasHeightForWidth())
        self.frame666.setSizePolicy(sizePolicy)
        self.frame666.setStyleSheet("QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}")
        self.frame666.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame666.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame666.setObjectName("frame666")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame666)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem21 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        self.frame_16 = QtWidgets.QFrame(self.frame666)
        self.frame_16.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.frame_16)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.editStuNum = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.editStuNum.setFont(font)
        self.editStuNum.setObjectName("editStuNum")
        self.horizontalLayout_16.addWidget(self.editStuNum)
        self.horizontalLayout_15.addWidget(self.frame_16)
        spacerItem22 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.frame_17 = QtWidgets.QFrame(self.frame666)
        self.frame_17.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.frame_17)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_17.addWidget(self.label_4)
        self.editStuName = QtWidgets.QLineEdit(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.editStuName.setFont(font)
        self.editStuName.setObjectName("editStuName")
        self.horizontalLayout_17.addWidget(self.editStuName)
        self.horizontalLayout_15.addWidget(self.frame_17)
        spacerItem23 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem23)
        self.frame_18 = QtWidgets.QFrame(self.frame666)
        self.frame_18.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_5 = QtWidgets.QLabel(self.frame_18)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.editStuAge = QtWidgets.QLineEdit(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.editStuAge.setFont(font)
        self.editStuAge.setObjectName("editStuAge")
        self.horizontalLayout_18.addWidget(self.editStuAge)
        self.horizontalLayout_15.addWidget(self.frame_18)
        spacerItem24 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem24)
        self.frame_19 = QtWidgets.QFrame(self.frame666)
        self.frame_19.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.frame_19)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_19.addWidget(self.label_6)
        self.cboSex = QtWidgets.QComboBox(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSex.setFont(font)
        self.cboSex.setObjectName("cboSex")
        self.horizontalLayout_19.addWidget(self.cboSex)
        self.horizontalLayout_15.addWidget(self.frame_19)
        spacerItem25 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem25)
        self.verticalLayout_9.addWidget(self.frame666)
        self.frame_42 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_42.sizePolicy().hasHeightForWidth())
        self.frame_42.setSizePolicy(sizePolicy)
        self.frame_42.setStyleSheet("QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem26 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem26)
        self.label_28 = QtWidgets.QLabel(self.frame_42)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.editPhone = QtWidgets.QLineEdit(self.frame_42)
        self.editPhone.setObjectName("editPhone")
        self.horizontalLayout_23.addWidget(self.editPhone)
        spacerItem27 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem27)
        self.label_29 = QtWidgets.QLabel(self.frame_42)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.editAddress = QtWidgets.QLineEdit(self.frame_42)
        self.editAddress.setObjectName("editAddress")
        self.horizontalLayout_23.addWidget(self.editAddress)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem28)
        self.verticalLayout_9.addWidget(self.frame_42)
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_20)
        self.formLayout_2.setContentsMargins(10, 0, 10, 15)
        self.formLayout_2.setSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_20)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget)
        self.verticalLayout_9.addWidget(self.frame_20)
        self.frame_20.raise_()
        self.frame_42.raise_()
        self.frame666.raise_()
        self.frame555.raise_()
        self.verticalLayout_5.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.stuInfoSetPage)
        self.resultInfoSetPage = QtWidgets.QWidget()
        self.resultInfoSetPage.setMinimumSize(QtCore.QSize(1038, 800))
        self.resultInfoSetPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resultInfoSetPage.setObjectName("resultInfoSetPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.resultInfoSetPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.resultInfoSetPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.cboSelectKind_4 = QtWidgets.QComboBox(self.frame_12)
        self.cboSelectKind_4.setGeometry(QtCore.QRect(99, 96, 120, 30))
        self.cboSelectKind_4.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSelectKind_4.setFont(font)
        self.cboSelectKind_4.setObjectName("cboSelectKind_4")
        self.btnUpdate = QtWidgets.QPushButton(self.frame_12)
        self.btnUpdate.setGeometry(QtCore.QRect(690, 30, 93, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdate.sizePolicy().hasHeightForWidth())
        self.btnUpdate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnUpdate_2 = QtWidgets.QPushButton(self.frame_12)
        self.btnUpdate_2.setGeometry(QtCore.QRect(690, 90, 93, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdate_2.sizePolicy().hasHeightForWidth())
        self.btnUpdate_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnUpdate_2.setFont(font)
        self.btnUpdate_2.setObjectName("btnUpdate_2")
        self.editResult_2 = QtWidgets.QLineEdit(self.frame_12)
        self.editResult_2.setGeometry(QtCore.QRect(527, 96, 140, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editResult_2.sizePolicy().hasHeightForWidth())
        self.editResult_2.setSizePolicy(sizePolicy)
        self.editResult_2.setMaximumSize(QtCore.QSize(140, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.editResult_2.setFont(font)
        self.editResult_2.setObjectName("editResult_2")
        self.label_15 = QtWidgets.QLabel(self.frame_12)
        self.label_15.setGeometry(QtCore.QRect(17, 96, 80, 30))
        self.label_15.setMinimumSize(QtCore.QSize(80, 0))
        self.label_15.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setGeometry(QtCore.QRect(231, 96, 80, 17))
        self.label_16.setMinimumSize(QtCore.QSize(80, 0))
        self.label_16.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setObjectName("label_16")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(17, 33, 80, 35))
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        self.label_11.setGeometry(QtCore.QRect(231, 33, 80, 35))
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setObjectName("label_11")
        self.cboSelectKind_5 = QtWidgets.QComboBox(self.frame_12)
        self.cboSelectKind_5.setGeometry(QtCore.QRect(313, 96, 120, 30))
        self.cboSelectKind_5.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSelectKind_5.setFont(font)
        self.cboSelectKind_5.setObjectName("cboSelectKind_5")
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        self.label_10.setGeometry(QtCore.QRect(445, 33, 80, 35))
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setObjectName("label_10")
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        self.label_17.setGeometry(QtCore.QRect(450, 90, 71, 31))
        self.label_17.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.cboSelectKind = QtWidgets.QComboBox(self.frame_12)
        self.cboSelectKind.setGeometry(QtCore.QRect(99, 35, 120, 30))
        self.cboSelectKind.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSelectKind.setFont(font)
        self.cboSelectKind.setObjectName("cboSelectKind")
        self.cboSelectKind_6 = QtWidgets.QComboBox(self.frame_12)
        self.cboSelectKind_6.setGeometry(QtCore.QRect(530, 29, 120, 41))
        self.cboSelectKind_6.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSelectKind_6.setFont(font)
        self.cboSelectKind_6.setObjectName("cboSelectKind_6")
        self.cboSelectKind_7 = QtWidgets.QComboBox(self.frame_12)
        self.cboSelectKind_7.setGeometry(QtCore.QRect(310, 30, 120, 41))
        self.cboSelectKind_7.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.cboSelectKind_7.setFont(font)
        self.cboSelectKind_7.setObjectName("cboSelectKind_7")
        self.verticalLayout_6.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.resultInfoSetPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_13)
        self.formLayout_3.setContentsMargins(5, 0, 5, 20)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_13)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_2)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.resultInfoSetPage)
        self.stuInfoQueryPage = QtWidgets.QWidget()
        self.stuInfoQueryPage.setObjectName("stuInfoQueryPage")
        self.formLayout_12 = QtWidgets.QFormLayout(self.stuInfoQueryPage)
        self.formLayout_12.setContentsMargins(0, 0, 0, 0)
        self.formLayout_12.setSpacing(0)
        self.formLayout_12.setObjectName("formLayout_12")
        self.frame_36 = QtWidgets.QFrame(self.stuInfoQueryPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        self.frame_36.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_37 = QtWidgets.QFrame(self.frame_36)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem29)
        self.label = QtWidgets.QLabel(self.frame_37)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_22.addWidget(self.label)
        self.cboSelect = QtWidgets.QComboBox(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSelect.sizePolicy().hasHeightForWidth())
        self.cboSelect.setSizePolicy(sizePolicy)
        self.cboSelect.setMinimumSize(QtCore.QSize(121, 31))
        self.cboSelect.setMaximumSize(QtCore.QSize(121, 31))
        self.cboSelect.setObjectName("cboSelect")
        self.horizontalLayout_22.addWidget(self.cboSelect)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem30)
        self.label_27 = QtWidgets.QLabel(self.frame_37)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.editKey = QtWidgets.QLineEdit(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editKey.sizePolicy().hasHeightForWidth())
        self.editKey.setSizePolicy(sizePolicy)
        self.editKey.setMinimumSize(QtCore.QSize(121, 31))
        self.editKey.setMaximumSize(QtCore.QSize(121, 31))
        self.editKey.setObjectName("editKey")
        self.horizontalLayout_22.addWidget(self.editKey)
        spacerItem31 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem31)
        self.btnQuery = QtWidgets.QPushButton(self.frame_37)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnQuery.setFont(font)
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout_22.addWidget(self.btnQuery)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem32)
        self.verticalLayout_17.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.frame_36)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.formLayout_13 = QtWidgets.QFormLayout(self.frame_38)
        self.formLayout_13.setContentsMargins(5, 0, 5, 20)
        self.formLayout_13.setSpacing(0)
        self.formLayout_13.setObjectName("formLayout_13")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.frame_38)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_7)
        self.verticalLayout_17.addWidget(self.frame_38)
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_36)
        self.stackedWidget.addWidget(self.stuInfoQueryPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout_14 = QtWidgets.QFormLayout(self.page)
        self.formLayout_14.setContentsMargins(0, 0, 0, 0)
        self.formLayout_14.setSpacing(0)
        self.formLayout_14.setObjectName("formLayout_14")
        self.frame_39 = QtWidgets.QFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_39.sizePolicy().hasHeightForWidth())
        self.frame_39.setSizePolicy(sizePolicy)
        self.frame_39.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_40 = QtWidgets.QFrame(self.frame_39)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_40.sizePolicy().hasHeightForWidth())
        self.frame_40.setSizePolicy(sizePolicy)
        self.frame_40.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QLabel{\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem33 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem33)
        self.label_24 = QtWidgets.QLabel(self.frame_40)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(120, 35))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_21.addWidget(self.lineEdit_9)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem34)
        self.label_25 = QtWidgets.QLabel(self.frame_40)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(120, 35))
        self.comboBox_2.setMaximumSize(QtCore.QSize(120, 35))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_21.addWidget(self.comboBox_2)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem35)
        self.label_26 = QtWidgets.QLabel(self.frame_40)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_40)
        self.comboBox_3.setMaximumSize(QtCore.QSize(100, 35))
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_21.addWidget(self.comboBox_3)
        spacerItem36 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem36)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_40)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_21.addWidget(self.pushButton_13)
        spacerItem37 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem37)
        self.verticalLayout_18.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_39)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_41.sizePolicy().hasHeightForWidth())
        self.frame_41.setSizePolicy(sizePolicy)
        self.frame_41.setStyleSheet("QTableWidget QHeaderView::section {\n"
"    background-color: rgb(227, 87, 255); /* 设置表头背景色 */\n"
"    padding: 5px; /* 内边距，可调整内容与边框间距 */\n"
"    border: 1px solid #ccc; /* 表头单元格边框 */\n"
"    text-align: center; /* 文本左对齐，也可设为center等 */\n"
"}\n"
"\n"
"QTableWidgetItem {\n"
"    font: 12pt \"楷体\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(202, 225, 255);\n"
"    font: 12pt \"黑体\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    padding-bottom:3px;\n"
"    padding-left:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(119, 144, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.formLayout_15 = QtWidgets.QFormLayout(self.frame_41)
        self.formLayout_15.setContentsMargins(5, 0, 5, 20)
        self.formLayout_15.setSpacing(0)
        self.formLayout_15.setObjectName("formLayout_15")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.frame_41)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_8)
        self.verticalLayout_18.addWidget(self.frame_41)
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.frame_39)
        self.stackedWidget.addWidget(self.page)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_4.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMaximized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "学生管理系统"))
        self.pushButton_5.setText(_translate("MainWindow", "首页"))
        self.pushButton_6.setText(_translate("MainWindow", "基础设置"))
        self.pushButton_7.setText(_translate("MainWindow", "信息设置"))
        self.pushButton_8.setText(_translate("MainWindow", "信息查询"))
        self.label_2.setText(_translate("MainWindow", "欢迎登录学生成绩管理系统\n"
"当前版本V1.0.0"))
        self.label_8.setText(_translate("MainWindow", "年级名称："))
        self.label_7.setText(_translate("MainWindow", "年级编号："))
        self.pushButton_9.setText(_translate("MainWindow", "添加"))
        self.label_19.setText(_translate("MainWindow", "选择年级"))
        self.label_14.setText(_translate("MainWindow", "班级编号"))
        self.label_18.setText(_translate("MainWindow", "班级名称"))
        self.pushButton_10.setText(_translate("MainWindow", "添加"))
        self.label_21.setText(_translate("MainWindow", "类别名称："))
        self.label_20.setText(_translate("MainWindow", "类别编号："))
        self.pushButton_11.setText(_translate("MainWindow", "添加"))
        self.label_23.setText(_translate("MainWindow", "科目名称："))
        self.pushButton_12.setText(_translate("MainWindow", "添加"))
        self.label_22.setText(_translate("MainWindow", "科目编号："))
        self.label_12.setText(_translate("MainWindow", "所属年级："))
        self.label_13.setText(_translate("MainWindow", "所属班级："))
        self.btnBush_2.setText(_translate("MainWindow", "刷新"))
        self.btnAdd_2.setText(_translate("MainWindow", "增加"))
        self.label_3.setText(_translate("MainWindow", "学生编号："))
        self.label_4.setText(_translate("MainWindow", "学生姓名："))
        self.label_5.setText(_translate("MainWindow", "年龄："))
        self.label_6.setText(_translate("MainWindow", "性别："))
        self.label_28.setText(_translate("MainWindow", "联系电话："))
        self.label_29.setText(_translate("MainWindow", "地址："))
        self.btnUpdate.setText(_translate("MainWindow", "刷新"))
        self.btnUpdate_2.setText(_translate("MainWindow", "增加"))
        self.label_15.setText(_translate("MainWindow", "学生姓名 "))
        self.label_16.setText(_translate("MainWindow", "考试科目"))
        self.label_9.setText(_translate("MainWindow", "考试种类 "))
        self.label_11.setText(_translate("MainWindow", "选择年级 "))
        self.label_10.setText(_translate("MainWindow", "选择班级 "))
        self.label_17.setText(_translate("MainWindow", "成  绩"))
        self.label.setText(_translate("MainWindow", "选择查询列表："))
        self.label_27.setText(_translate("MainWindow", "查询关键字："))
        self.btnQuery.setText(_translate("MainWindow", "查询"))
        self.label_24.setText(_translate("MainWindow", "学生姓名："))
        self.label_25.setText(_translate("MainWindow", "考试种类"))
        self.label_26.setText(_translate("MainWindow", "考试科目"))
        self.pushButton_13.setText(_translate("MainWindow", "查询"))
